title: Ruby on Wheels
header-img: assets/images/home.jpg
email: jakob.class@gmail.com
description: A developer on the road.
github_username:  mikrobi
email_username:  jakob.class@gmail.com

paginate_path: "blog/page:num/"
permalink: blog/:title/
paginate: 10

plugins: [jekyll-paginate, jekyll-feed, jemoji, jekyll-sitemap]
sass:
  style: compressed
