title: Ruby on Wheels
header-img: assets/images/home.jpg
email: jakob.class@gmail.com
description: A developer on the road.
github_username:  mikrobi
email_username:  jakob.class@gmail.com


google_tracking_id: "UA-105302462-1"

paginate_path: "blog/page:num/"
permalink: blog/:title/
paginate: 10

gems: [jekyll-paginate, jekyll-feed, jemoji]
sass:
  style: compressed
